"use client"

import { Inter } from "next/font/google";
import { AuthProvider } from "./contexts/AuthContext";
import "./globals.css";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "MetaGo Barber",
//   description: "Generated by create next app",
//   icons: '/logo.png'
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ligth`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
